language: php

php:
  - 5.6
  - 7
  - 7.1

env:
  - TYPO3_VERSION=^6.2.0
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=dev-master

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - .Build/bin/phpcs --standard=PSR2 --extensions=php *
