<?php

########################################################################
# Extension Manager/Repository config file for ext: "sz_ebook"
#
# Auto generated by Extension Builder 2014-06-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'eBook',
	'description' => 'Converts PDF\'s to eBook, using turn.js. Visist us on http://www.sunzinet.com/ Visit us on <a href="http://www.sunzinet.com/" target="_blank">sunzinet AG</a> - <a href="http://www.sunzinet.com/typo3-agentur.html" target="_blank">Typo3 Agentur</a>',
	'category' => 'plugin',
	'author' => 'Dennis Römmich',
	'author_email' => 'dennis.roemmich@sunzinet.com',
	'author_company' => 'sunzinet AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.3',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5.0-6.2.99',
			'Imagick'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>